services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-build:/app/build

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-build:/usr/share/nginx/html:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - app

volumes:
  app-build: